-- Alex Zaharia
-- azaharia@calpoly.edu
-- Apr 19, 2023

CREATE TABLE appelation (
  Num INT NOT NULL,
  Appelation VARCHAR(255) NOT NULL,
  County VARCHAR(255) NOT NULL,
  AState VARCHAR(255) NOT NULL,
  Area VARCHAR(255) NOT NULL,
  isAVA VARCHAR(255) NOT NULL
);

CREATE TABLE grapes (
  GrapeID INTEGER PRIMARY KEY,
  Grape VARCHAR(255) NOT NULL,
  Color VARCHAR(255) NOT NULL
);

CREATE TABLE wine (
  Num INTEGER PRIMARY KEY,
  GrapeID INTEGER NOT NULL,
  Winery VARCHAR(255) NOT NULL,
  Appelation VARCHAR(255) NOT NULL,
  WState VARCHAR(255) NOT NULL,
  WName VARCHAR(255) NOT NULL,
  WYear INTEGER NOT NULL,
  Price INTEGER NOT NULL,
  Score INTEGER NOT NULL,
  Cases INTEGER NOT NULL,
  Drink VARCHAR(255) NOT NULL,
  FOREIGN KEY (GrapeID) REFERENCES grapes(GrapeID)
);